"""change_ip_length

Revision ID: c945fe00daeb
Revises: 13a9421b19d9
Create Date: 2024-05-04 03:30:17.311752

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c945fe00daeb"
down_revision: str | None = "13a9421b19d9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "recaptcha_log",
        "ip_addr",
        existing_type=sa.VARCHAR(length=15),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "recaptcha_log",
        "ip_addr",
        existing_type=sa.String(length=64),
        type_=sa.VARCHAR(length=15),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
